### ISSUE TITLE
Trying to get server ID for a dropdown menu

### ISSUE THREAD

**Issue by timgavin** [praxisnetau/serverpilot-api#1]
I'm using Laravel, and am creating a dropdown menu so customers can select their server when creating new apps. I want the menu to be real simple, something like:

```
<select name="server_id">
    <option value="{{ SERVER_ID }}">{{ SERVER NAME }}</option>
</select>
```

Here's the code I'm using to build the array

```
<?php

namespace App;

use ServerPilot\ServerPilotAPI;
use Illuminate\Database\Eloquent\Model;

class ServerPilot extends Model
{
    public static function listServers($option = null)
    {
        $sp = ServerPilotAPI::inst('MY_ID', 'MY_KEY');
        $servers = $sp->servers->listAll();

        if($option == 'dropdown') {

            $array = [];

            foreach($servers as $server) {
                dd($server->id); // just trying to see the value...
                $array[$value->id] = $value->name;
            }

            return $array;
        }

        return $servers;
    }
}
```

However, when running that code I receive the following error 

```
Cannot access protected property ServerPilot\Model\Server::$id
```

How can I retrieve the `ID` and `name` of the servers without having to do a lookup for each during the loop?

**Comment by colintucker** [comment]
Hi @timgavin - the properties are protected from direct access, so try using the accessor methods, i.e.:

`$value->getID()` and `$value->getName()`

That should work.

**Comment by timgavin** [comment]
Perfect, thanks!
