### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by timgavin** [praxisnetau/serverpilot-api#2]
I'm trying to creat an app and keep receiving the following error

```
Array to string conversion
```

I'm just trying to do something real basic and it won't let me.

```
$sp = ServerPilotAPI::inst('MYCID', 'MYKEY');

$app = $sp->apps->create('shemphoward', 'I0F3Gn9GBsVl9YOs', 'php7.0', ['shemphoward.com']);
```

Tried it like this too. No luck

```
$app = $sp->apps->create('shemphoward', 'I0F3Gn9GBsVl9YOs', 'php7.0', 'shemphoward.com');
```

**Comment by colintucker** [comment]
Hi Tim,

Looks like the optional Wordpress param was being converted to a string from an array.  This should be fixed with commit 2548914 - can you give it a try please?

Thanks.

**Comment by timgavin** [comment]
I ran `composer update` but the change wasn't reflected, so I added it manually. Changing `(string)` to `(array)` solved that problem, but now it seems wordpress is not optional.

```
API returned error 400: "You must provide a object value for 'wordpress'."
```

Related to the composer issue, here's my composer file...

```
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "praxisnetau/serverpilot-api": "~1.0"
    },
```

**Comment by colintucker** [comment]
You'd have to update to `dev-master`.

Ahh object data type instead of array!  >_<
OK give me a few minutes!

**Comment by colintucker** [comment]
Hi @timgavin - OK I believe it has been fixed, can you please try commit e6a6f1e

**Comment by timgavin** [comment]
Working with and without Wordpress arguments! Thanks!

**Comment by colintucker** [comment]
Excellent! Sorry for the hassle, I should have picked that up in testing. 👍
